version: '3'
services:
  mysql-db:
    image: mysql:5.7
    hostname: mysql-db
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: 'abhioli'
      MYSQL_USER: 'user_abioli'
      MYSQL_PASSWORD: 'passwd123'
      MYSQL_ROOT_PASSWORD: 'passwordroot'
    ports:
      - '3307:3306'
    volumes:
      - my-db-volume:/var/lib/mysql
volumes:
  my-db-volume:
